### ISSUE TITLE
setjmp doesn't work

### ISSUE THREAD

**Issue by szmodz** [espressif/newlib-esp32#5]
Moved:
https://github.com/espressif/esp-idf/issues/4541

**Comment by szmodz** [comment]
I think the implementation should be reviewed carefully, since it may have more issues.

**Comment by igrr** [comment]
_JBLEN is in the units of words (so `12*4+4*4+4 = 17 * 4` bytes) so it looks correct.

https://github.com/espressif/newlib-esp32/blob/1b349a3f9e6303067f1ca239db881bf8dd0d511a/newlib/libc/include/machine/setjmp.h#L421

**Comment by szmodz** [comment]
Yes, I figured that out, that's why I closed the issue. Still, setjmp doesn't work.
